import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const read = (relative) => fs.readFileSync(new URL(`../${relative}`, import.meta.url), 'utf8')

test('team challenge leaderboard restores stack rank, team drill-down, member email, and nine-hole awareness', () => {
  const challenges = read('src/pages/Challenges.tsx')
  const styles = read('src/index.css')
  assert.match(challenges, /aria-label="Team Challenge stack rank"/)
  assert.match(challenges, /team_stack_rank_selected/)
  assert.match(challenges, /openTeamLeaderboardRoundSummary\(message, row\.side\)/)
  assert.match(challenges, /<span className="small">\{member\.email \|\| 'Email not available'\}<\/span>/)
  assert.match(challenges, /getTeamChallengeDisplayHoleCount/)
  assert.match(challenges, /of \{holeNumbers\.length\} holes have scores from both teams/)
  assert.match(styles, /\.inboxTeamRankings/)
})

test('tournament builder and registration enforce a configured team size from two through four', () => {
  const fields = read('src/components/TournamentTemplateFields.tsx')
  const templates = read('src/lib/tournament-templates.ts')
  const portal = read('src/pages/TournamentPortal.tsx')
  const server = read('server/index.js')
  const rbac = read('server/lib/rbac.js')
  assert.match(fields, /Players on a team/)
  assert.match(fields, /TOURNAMENT_TEAM_SIZE_OPTIONS\.map/)
  assert.match(templates, /TOURNAMENT_TEAM_SIZE_OPTIONS = \[2, 3, 4\]/)
  assert.match(templates, /tournamentTeamSize\?: number/)
  assert.match(portal, /eligibleTeams = useMemo\(\(\) => teams\.filter/)
  assert.match(portal, /requiredTeammateCount/)
  assert.match(portal, /This tournament requires exactly \{requiredTeamSize\} players per team/)
  assert.match(server, /resolveRegistrationTeam\(pool, req\.body \|\| \{\}, req\.user, requiredTeamSize\)/)
  assert.match(server, /Tournament teams must have exactly \$\{normalizedRequiredTeamSize\} players for this tournament/)
  assert.match(rbac, /tournamentTeamSize:/)
})

test('notification groups require validated GolfHomiez users, can invite missing users, and soft-delete without deleting messages', () => {
  const inbox = read('src/pages/Inbox.tsx')
  const notifications = read('src/lib/notifications.ts')
  const service = read('server/lib/notification-service.js')
  const server = read('server/index.js')
  const migration = read('migration_scripts/20260824_078_message_group_soft_delete.sql')
  assert.match(inbox, /validateGroupMember/)
  assert.match(inbox, /lookupUserByEmail/)
  assert.match(inbox, /InviteHomieModal/)
  assert.match(inbox, /They were not added to the group/)
  assert.match(inbox, /Delete group/)
  assert.match(notifications, /deleteMessageGroup/)
  assert.match(server, /app\.delete\('\/api\/message-groups\/:id'/)
  assert.match(service, /UPDATE message_groups SET deleted_at = CURRENT_TIMESTAMP\(6\)/)
  assert.doesNotMatch(service, /DELETE FROM inbox_messages[^\n]*group/i)
  assert.match(migration, /ADD COLUMN deleted_at DATETIME\(6\) NULL/)
})

test('challenge notifications identify sender and timestamp in the shared discussion thread', () => {
  const inbox = read('src/pages/Inbox.tsx')
  assert.match(inbox, /Challenge discussion thread/)
  assert.match(inbox, /threadMessage\.senderEmail/)
  assert.match(inbox, /formatTimestamp\(threadMessage\.createdAt\)/)
})

test('my golf scores hides Clear filters until a score filter is active while home omits score filters', () => {
  const home = read('src/pages/Home.tsx')
  const scores = read('src/pages/MyGolfScores.tsx')

  assert.doesNotMatch(home, /scoreFiltersClear|hasActiveScoreFilters|scoreFilterToolbar/)
  assert.match(scores, /const hasActiveScoreFilters = stateFilter !== 'all' \|\| courseFilter !== 'all' \|\| teamFilter !== 'all'/)
  assert.match(scores, /\{hasActiveScoreFilters \? <button type="button" className="scoreFiltersClear"/)
})

test('tournament round summary respects a persisted nine-hole scorecard', () => {
  const scoreModal = read('src/components/TournamentTeamScoreModal.tsx')
  assert.match(scoreModal, /const holeLimit = normalizedHoles\.length === 9/)
  assert.match(scoreModal, /defaultHoles\.slice\(0, holeLimit\)/)
  assert.match(scoreModal, /const holeCount = nextHoles\.length === 9 \? 9 : 18/)
})


test('team builder requires first and last name for invited golfers who are not registered yet', () => {
  const teams = read('src/pages/Teams.tsx')
  const teamUtils = read('server/lib/team-utils.js')
  const server = read('server/index.js')
  assert.match(teams, /First name for invited teammates/)
  assert.match(teams, /Last name for invited teammates/)
  assert.match(teams, /Add this golfer's first and last name before saving the team/)
  assert.match(teams, /manualNameRequired/)
  assert.doesNotMatch(teamUtils, /\|\| \(email \? email\.split\('@'\)\[0\]/)
  assert.match(server, /invited_member_first_last_name_required/)
  assert.match(server, /First name and last name are required for team members who do not have a GolfHomiez account/)
})

test('notification group builder removes missing-account draft members and keeps feedback beside group controls', () => {
  const inbox = read('src/pages/Inbox.tsx')
  const styles = read('src/index.css')
  assert.match(inbox, /current\.filter\(\(item\) => item\.id !== memberId\)/)
  assert.match(inbox, /draftLineRemoved: true/)
  assert.match(inbox, /addMemberInputCleared: true/)
  assert.match(inbox, /groupMemberFeedback/)
  assert.match(inbox, /groupBuilderFeedback/)
  assert.match(inbox, /groupFeedbackById/)
  assert.match(inbox, /They were not added to the group; add them after they register for GolfHomiez/)
  assert.match(styles, /\.messageGroupActionFeedback/)
})

test('completed tournament leaderboard exposes compact team-member names beneath team names', () => {
  const portal = read('src/pages/TournamentPortal.tsx')
  const accounts = read('src/lib/accounts.ts')
  const leaderboard = read('server/lib/tournament-final-leaderboard.js')
  const styles = read('src/index.css')
  assert.match(portal, /tournament-final-leaderboard-team-members/)
  assert.match(portal, /row\.teamMemberNames\.join\(' · '\)/)
  assert.match(accounts, /teamMemberNames\?: string\[\]/)
  assert.match(leaderboard, /normalizeTeamMemberNames/)
  assert.match(styles, /\.tournament-final-leaderboard-team-members/)
})

test('host course events share the public course calendar while tournament course misc stays host and organizer private', () => {
  const hostPortal = read('src/pages/HostPortal.tsx')
  const calendarPage = read('src/pages/GolfCourseCalendarPage.tsx')
  const coursePage = read('src/pages/GolfCoursePage.tsx')
  const fields = read('src/components/TournamentTemplateFields.tsx')
  const hostOrganizer = read('src/pages/OrganizerTournaments.tsx')
  const accounts = read('src/lib/accounts.ts')
  const server = read('server/index.js')
  const rbac = read('server/lib/rbac.js')
  const migration = read('migration_scripts/20260903_084_course_calendar_events.sql')
  const migrations = read('server/migrations/index.js')
  const styles = read('src/index.css')
  const packageJson = read('package.json')

  const createTournamentIndex = hostPortal.indexOf('data-testid="host-create-tournament-section"')
  const courseEventsIndex = hostPortal.indexOf('data-testid="host-course-event-section"')
  const hostAdminIndex = hostPortal.indexOf('data-testid="host-admin-section"')
  assert.ok(courseEventsIndex >= 0 && createTournamentIndex > courseEventsIndex)
  assert.ok(hostAdminIndex > createTournamentIndex)
  assert.doesNotMatch(hostPortal, /data-testid="host-course-calendar-section"/)

  assert.match(hostPortal, /Add course event/)
  assert.match(hostPortal, /This event will be visible to the public on the golf-course calendar/)
  assert.doesNotMatch(hostPortal, /hostCourseEventRowDetails/)
  assert.match(accounts, /fetchHostCourseEvents/)
  assert.match(accounts, /createHostCourseEvent/)
  assert.match(server, /app\.post\('\/api\/host\/course-events'/)
  assert.match(server, /host_course_event_created/)
  assert.match(server, /correlationId: req\.correlationId/)
  assert.match(migration, /CREATE TABLE IF NOT EXISTS golf_course_events/)
  assert.match(migration, /correlation_id VARCHAR\(191\)/)
  assert.match(migrations, /version: '20260903_084'/)
  assert.match(packageJson, /"postinstall": "npm run cleanup:project-files && npm run db:migrate && npm run build"/)

  assert.match(calendarPage, /Course event/)
  assert.match(calendarPage, /golfCourseCalendarEvent--courseEvent/)
  assert.match(styles, /\.golfCourseCalendarEvent--courseEvent/)
  assert.match(styles, /\.golfCourseCalendarLegendCourseEvent/)
  assert.match(styles, /\.hostCourseEventRow\{[\s\S]*padding:7px 9px/)
  assert.match(styles, /\.golfCourseUpcomingEventRow\{[\s\S]*min-height:34px/)
  assert.match(styles, /overflow:visible/)
  assert.match(coursePage, /Upcoming events/)
  assert.match(coursePage, /UPCOMING_CALENDAR_ITEM_LIMIT = 5/)
  assert.match(coursePage, /\.slice\(0, UPCOMING_CALENDAR_ITEM_LIMIT\)/)
  assert.doesNotMatch(coursePage, /\{event\.details \?/)
  assert.match(coursePage, /upcoming_course_event_selected/)

  assert.match(fields, /Tournament Course Misc/)
  assert.match(fields, /who has paid|paid, special arrangements/i)
  assert.match(hostPortal, /<TournamentCourseMiscField/)
  assert.match(hostOrganizer, /<TournamentCourseMiscField/)
  assert.match(server, /stripPrivateTournamentTemplateData/)
  assert.match(server, /delete publicTemplateData\.tournamentCourseMisc/)
  assert.match(rbac, /listAllTournaments[\s\S]*stripTournamentCourseMisc/)
})

test('mobile score entry resumes the active challenge or solo hole after a page reload', () => {
  const challenge = read('src/pages/Challenges.tsx')
  const solo = read('src/pages/SoloLogger.tsx')
  const scoreFlowState = read('src/lib/score-flow-state.ts')

  assert.match(scoreFlowState, /gh\.scoreFlow\.challenge\./)
  assert.match(scoreFlowState, /gh\.scoreFlow\.solo\./)
  assert.match(scoreFlowState, /sessionStorage/)
  assert.match(scoreFlowState, /SCORE_FLOW_TTL_MS = 12 \* 60 \* 60 \* 1000/)
  assert.doesNotMatch(scoreFlowState, /localStorage/)

  assert.match(challenge, /loadChallengeScoreFlowState\(user\.id\)/)
  assert.match(challenge, /challenge_score_flow_restored_after_page_reload/)
  assert.match(challenge, /setExpandedThreadId\(thread\.threadId\)/)
  assert.match(challenge, /\[challengeSectionKey\(message, 'score'\)\]: true/)
  assert.match(challenge, /setActiveTeamChallengeScorecard\(\{ message, side: restored\.side \}\)/)
  assert.match(challenge, /setActiveIndividualChallengeScorecard\(\{ message, participant \}\)/)
  assert.match(challenge, /onActiveHoleChange=\{\(holeNumber\) => rememberTeamChallengeScoreFlow/)
  assert.match(challenge, /onActiveHoleChange=\{\(holeNumber\) => rememberIndividualChallengeScoreFlow/)
  assert.match(challenge, /clearPersistedChallengeScoreFlow\('team_modal_close'/)
  assert.match(challenge, /individual_modal_close_\$\{reason\}/)

  assert.match(solo, /loadSoloScoreFlowState\(userId\)/)
  assert.match(solo, /useLayoutEffect\(\(\) =>/)
  assert.match(solo, /solo_score_flow_restored_after_page_reload/)
  assert.match(solo, /initialHoleNumber=\{scorecardResumeHole\}/)
  assert.match(solo, /onActiveHoleChange=\{\(holeNumber\) => setScorecardResumeHole\(holeNumber\)\}/)
  assert.match(solo, /saveSoloScoreFlowState\(user\.id/)
  assert.match(solo, /clearSoloScoreFlowState\(user\?\.id\)/)
})

test('frontend lifecycle diagnostics retain the shared correlation id across mobile app switching', () => {
  const frontendLogger = read('src/lib/frontend-logger.ts')
  const serverLogger = read('server/lib/logger.js')

  assert.match(frontendLogger, /CORRELATION_STORAGE_KEY = 'gh\.correlationId'/)
  assert.match(frontendLogger, /X-Correlation-Id/)
  assert.match(frontendLogger, /addEventListener\?\.\('pageshow'/)
  assert.match(frontendLogger, /addEventListener\?\.\('pagehide'/)
  assert.match(frontendLogger, /addEventListener\?\.\('visibilitychange'/)
  assert.match(frontendLogger, /runtime\.lifecycle/)
  assert.match(frontendLogger, /navigationType/)

  assert.match(serverLogger, /access\.log/)
  assert.match(serverLogger, /api\.log/)
  assert.match(serverLogger, /frontend\.log/)
  assert.match(serverLogger, /error\.log/)
  assert.match(serverLogger, /correlationId/)
})

test('database migrations remain part of npm install and mobile score resume needs no schema dependency', () => {
  const packageJson = JSON.parse(read('package.json'))
  const scoreFlowState = read('src/lib/score-flow-state.ts')

  assert.equal(packageJson.scripts.postinstall, 'npm run cleanup:project-files && npm run db:migrate && npm run build')
  assert.match(scoreFlowState, /sessionStorage/)
  assert.doesNotMatch(scoreFlowState, /fetch\(|\/api\//)
})

test('existing-round hole editor resumes its active hole and scorecard loads never overwrite newer saved holes', () => {
  const myScores = read('src/pages/MyGolfScores.tsx')
  const roundDetail = read('src/components/RoundDetailModal.tsx')
  const holeScorecard = read('src/components/HoleByHoleScorecard.tsx')
  const scoreFlowState = read('src/lib/score-flow-state.ts')

  assert.match(scoreFlowState, /gh\.scoreFlow\.roundEdit\./)
  assert.match(scoreFlowState, /loadRoundEditScoreFlowState/)
  assert.match(scoreFlowState, /saveRoundEditScoreFlowState/)
  assert.match(scoreFlowState, /clearRoundEditScoreFlowState/)

  assert.match(myScores, /loadRoundEditScoreFlowState\(user\?\.id\)/)
  assert.match(myScores, /active_round_editor_restored_after_page_reload/)
  assert.match(myScores, /setSelectedRound\(resumedRound\)/)
  assert.match(myScores, /scoreFlowUserId=\{user\?\.id\}/)

  assert.match(roundDetail, /round_edit_scorecard_restored_after_page_reload/)
  assert.match(roundDetail, /initialHoleNumber=\{resumeActiveHole\}/)
  assert.match(roundDetail, /onActiveHoleChange=\{handleActiveEditHoleChange\}/)
  assert.match(roundDetail, /round_edit_scorecard_resume_state_saved/)
  assert.match(roundDetail, /cleared_after_round_persist/)
  assert.match(roundDetail, /\/api\/scorecard-drafts\?\$\{params\.toString\(\)\}/)

  assert.match(holeScorecard, /const holesRef = useRef<HoleScoreDetail\[]>\(holes\)/)
  assert.match(holeScorecard, /latestPersistedHolesAfterLoad = persistedHolesRef\.current/)
  assert.match(holeScorecard, /latestRenderedHoles = holesRef\.current/)
  assert.match(holeScorecard, /late_state_reconciled/)
  assert.match(holeScorecard, /preventedStaleLoadOverwrite: true/)
})

test('background auth refresh cannot unmount an active protected scorecard', () => {
  const protectedRoute = read('src/components/ProtectedRoute.tsx')
  const authContext = read('src/context/AuthContext.tsx')

  assert.match(protectedRoute, /const \{ user, loading, hasRole, needsProfileEnrichment, billingStatus \} = useAuth\(\)/)
  assert.match(protectedRoute, /if \(loading\) return <div className="container"><div className="card">Loading\.\.\.<\/div><\/div>/)
  assert.doesNotMatch(protectedRoute, /loading \|\| profileStatusLoading \|\| billingStatusLoading/)

  assert.match(authContext, /document\.visibilityState === 'hidden'/)
  assert.match(authContext, /activity_ttl_refresh_skipped_hidden/)
  assert.match(authContext, /activity_ttl_refresh_started/)
  assert.match(authContext, /visibilityState: typeof document === 'undefined' \? null : document\.visibilityState/)
  assert.match(authContext, /\['click', 'keydown', 'focus', 'visibilitychange'\]/)
})

test('guest navigation exposes golf-course login and account creation in the requested order', () => {
  const nav = read('src/components/NavBar.tsx')
  const loginIndex = nav.indexOf('>Golf Course Login</NavLink>')
  const createIndex = nav.indexOf('>Create Golf Course Account</NavLink>')
  const organizerIndex = nav.indexOf('>Organizer Login</NavLink>')
  assert.ok(loginIndex >= 0, 'Golf Course Login navigation item should be present')
  assert.ok(createIndex > loginIndex, 'Create Golf Course Account should appear below Golf Course Login')
  assert.ok(organizerIndex > createIndex, 'Create Golf Course Account should appear before Organizer Login')
  assert.match(nav, /to="\/host\/register"[\s\S]*Create Golf Course Account/)
  assert.doesNotMatch(nav, />Host Login<\/NavLink>/)
})

test('existing golf-course primary host receives new account requests and any course host can review them', () => {
  const adminPortal = read('server/lib/admin-portal.js')
  const server = read('server/index.js')
  const hostPortal = read('src/pages/HostPortal.tsx')
  const hostAuth = read('src/lib/host-auth.ts')
  const createHost = read('src/pages/CreateHostAccount.tsx')
  const adminUi = read('src/pages/AdminPortal.tsx')
  const migration = read('migration_scripts/20260904_085_host_course_account_request_approval.sql')
  const migrations = read('server/migrations/index.js')
  const packageJson = read('package.json')

  assert.match(adminPortal, /findPrimaryHostAccountForCourse/)
  assert.match(adminPortal, /is_validated = 1[\s\S]*is_course_admin = 1/)
  assert.match(adminPortal, /approvalRoute = primaryHost \? 'course_primary_host' : 'golfhomiez_admin'/)
  assert.match(adminPortal, /sendHostAccountRequestRoutedEmail/)
  assert.match(adminPortal, /current primary golf-course account admin/)
  assert.match(adminPortal, /sendPrimaryHostAccountRequestNotification/)
  assert.match(adminPortal, /buildHostLoginUrl\(\)/)
  assert.match(adminPortal, /approve or deny this request/)
  assert.match(adminPortal, /export async function listHostAccountRequestsForHost/)
  assert.match(adminPortal, /export async function reviewHostAccountRequestByHost/)
  assert.match(adminPortal, /Golf-course account request is routed to the current course host for approval/)
  assert.match(adminPortal, /COALESCE\(approval_route, 'golfhomiez_admin'\) = 'golfhomiez_admin'/)

  assert.match(server, /pendingHostAccountRequests = await listHostAccountRequestsForHost/)
  assert.match(server, /app\.post\('\/api\/host\/account-requests\/:id\/review', hostAuthMiddleware/)
  assert.match(server, /host_account_request_review_completed/)
  assert.match(hostAuth, /reviewHostAccountRequest/)
  assert.match(hostPortal, /Pending golf-course account requests/)
  assert.match(hostPortal, /Any existing host for this course can approve or deny a request/)
  assert.match(hostPortal, /host_account_request_review_started/)
  assert.match(hostPortal, /onReviewHostAccountRequest\(request, 'approve'\)/)
  assert.match(hostPortal, /onReviewHostAccountRequest\(request, 'deny'\)/)
  assert.match(createHost, /approvalRoute === 'course_primary_host'/)
  assert.match(createHost, /primaryHostName/)
  assert.match(adminUi, /Routed to course host/)
  assert.match(adminUi, /Course host approval pending/)

  assert.match(migration, /ADD COLUMN approval_route VARCHAR\(32\)/)
  assert.match(migration, /ADD COLUMN routed_host_account_id VARCHAR\(191\)/)
  assert.match(migration, /ADD COLUMN reviewed_by_host_account_id VARCHAR\(191\)/)
  assert.match(migrations, /version: '20260904_085'/)
  assert.match(packageJson, /"postinstall": "npm run cleanup:project-files && npm run db:migrate && npm run build"/)
})

test('host tournament rows use compact workflow actions, safe registration preview, and a smaller red archive action', () => {
  const hostLine = read('src/components/TournamentManagementLineItem.tsx')
  const css = read('src/index.css')

  assert.match(hostLine, /tournament-management-line__badge--\$\{archived \? 'archived' : normalizedStatus/)
  assert.match(hostLine, /<strong className="tournament-management-line__url-text">\{tournamentUrl\}<\/strong>/)
  assert.doesNotMatch(hostLine, /<a href=\{tournamentUrl\}/)
  assert.match(hostLine, /Preview golfer registration URL in a new tab/)
  assert.match(hostLine, /window\.open\(tournamentUrl, '_blank', 'noopener,noreferrer'\)/)
  assert.match(hostLine, /preview_tournament_registration_url/)
  const previewIndex = hostLine.indexOf('tournament-management-line__preview')
  const copyIndex = hostLine.indexOf('tournament-management-line__copy')
  assert.ok(previewIndex >= 0 && copyIndex > previewIndex, 'Preview control must appear above/before the copy control')
  assert.match(css, /\.tournament-management-line \{[\s\S]*padding: 10px 12px;/)
  assert.match(css, /\.tournament-management-line__archive-button \{[\s\S]*padding: 6px 9px;[\s\S]*border-radius: 9px;[\s\S]*background: #fde8e8;[\s\S]*font-size: 12px;/)
  assert.match(css, /\.tournament-management-line__actions \{[\s\S]*display: flex;/)
  assert.match(css, /\.tournament-management-line__url-actions\{[\s\S]*flex-direction:column;/)
})

test('published tournaments expose a dedicated 30-second live leaderboard without hole-by-hole score data', async () => {
  const server = read('server/index.js')
  const hostLine = read('src/components/TournamentManagementLineItem.tsx')
  const hostPortal = read('src/pages/HostPortal.tsx')
  const organizerPortal = read('src/pages/OrganizerTournaments.tsx')
  const app = read('src/App.tsx')
  const page = read('src/pages/TournamentLeaderboard.tsx')
  const css = read('src/index.css')
  const accounts = read('src/lib/accounts.ts')
  const leaderboardSource = read('server/lib/tournament-final-leaderboard.js')

  assert.match(hostLine, /normalizedStatus === 'published'/)
  assert.doesNotMatch(hostLine, /getTournamentQrCodeUrl/)
  assert.doesNotMatch(hostLine, /tournament-management-line__qr-section/)
  assert.doesNotMatch(hostLine, /QR CODE/)
  assert.match(hostLine, /\/tournaments\/\$\{encodeURIComponent\(publicTournamentId\)\}\/leaderboard/)
  const leaderboardIndex = hostLine.indexOf('>Leaderboard</a>')
  const archiveIndex = hostLine.indexOf("busy ? 'Archiving…' : 'Archive'")
  assert.ok(leaderboardIndex >= 0 && archiveIndex > leaderboardIndex, 'Leaderboard action must appear to the left of Archive')
  assert.match(hostPortal, /showPublishedLeaderboard/)
  assert.doesNotMatch(organizerPortal, /showPublishedLeaderboard/)

  assert.match(app, /path="\/tournaments\/:id\/leaderboard" element=\{<TournamentLeaderboard \/>\}/)
  assert.match(app, /tournamentLeaderboardDisplay = \/\^\\\/tournaments/)
  assert.match(app, /!tournamentLeaderboardDisplay \? <NavBar \/> : null/)
  assert.match(accounts, /fetchTournamentLiveLeaderboard/)
  assert.match(server, /app\.get\('\/api\/tournament-portals\/:id\/leaderboard'/)
  assert.match(server, /refreshIntervalSeconds: 30/)
  assert.match(server, /holeByHoleIncluded: false/)
  assert.match(server, /tournament_live_leaderboard_loaded/)
  assert.match(page, /LIVE_LEADERBOARD_REFRESH_MS = 30_000/)
  assert.match(page, /GolfHomiezEmblem\.png/)
  assert.match(page, /className="leaderboardBrandIcon"/)
  assert.ok(page.indexOf('leaderboardBrandIcon') < page.indexOf("refreshing ? 'Refreshing…' : 'Live'"), 'Golf Homiez icon must appear above the Live status')
  assert.match(css, /\.leaderboardPage\{[\s\S]*background:#cdf7dd;/)
  assert.match(css, /\.leaderboardBrandIcon\{[\s\S]*width:64px;/)
  assert.match(page, /Round Score/)
  assert.match(page, /Thru/)
  assert.match(page, /Total Strokes/)
  assert.doesNotMatch(page, /row\.holes/)
  assert.doesNotMatch(page, /teamMemberNames/)
  assert.match(leaderboardSource, /buildTournamentLiveLeaderboardRows/)

  const { buildTournamentLiveLeaderboardRows } = await import('../server/lib/tournament-final-leaderboard.js')
  const registrations = [
    { id: 'r1', teamId: 't1', teamName: 'Birdies', teamMembers: [{ name: 'A Golfer' }] },
    { id: 'r2', teamId: 't2', teamName: 'Eagles', teamMembers: [{ name: 'B Golfer' }] },
  ]
  const scoreRows = [
    { team_key: 'team:t1', team_id: 't1', team_name: 'Birdies', holes_json: JSON.stringify([{ hole: 1, par: 4, score: 4, scoreProvided: true }, { hole: 2, par: 4, score: 4, scoreProvided: true }]), total_score: 8 },
    { team_key: 'team:t2', team_id: 't2', team_name: 'Eagles', holes_json: JSON.stringify([{ hole: 1, par: 4, score: 3, scoreProvided: true }, { hole: 2, par: 4, score: 4, scoreProvided: true }]), total_score: 7 },
  ]
  const rows = buildTournamentLiveLeaderboardRows(registrations, scoreRows)
  assert.equal(rows[0].teamName, 'Eagles')
  assert.equal(rows[0].roundLabel, '-1')
  assert.equal(rows[1].roundLabel, 'Par')
  assert.equal(rows[1].thru, 2)
  assert.equal(rows[1].totalScore, 8)
  assert.equal('holes' in rows[0], false)
  assert.equal('teamMemberNames' in rows[0], false)
})
