-- Correct Oquirrh Hills Golf Course hole par and yardage from the official Tooele City course scorecard.
-- Source reviewed 2026-09-16: https://golf.tooelecity.gov/the_course/index.php

INSERT INTO golf_courses
  (id, external_course_id, source, name, normalized_name, state_code, state_name, city, country, course_type,
   holes_count, par_total, total_yardage, address, postal_code, phone, website, is_manual, active, imported_at)
SELECT
  'oquirrh-hills-tooele-ut', '9e7dfbad-41a3-43b8-a47b-1740c11cf3db', 'tooele-city-correction',
  'Oquirrh Hills Golf Course', 'oquirrh hills golf course', 'UT', 'Utah', 'Tooele', 'US', 'Municipal',
  18, 72, 6591, '1255 East Vine Street', '84074', '435.882.4220', 'https://golf.tooelecity.gov/the_course/index.php', 0, 1, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
  SELECT 1 FROM golf_courses
   WHERE external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db'
      OR (state_code = 'UT' AND LOWER(name) = 'oquirrh hills golf course')
);

UPDATE golf_courses
SET holes_count = 18, par_total = 72, total_yardage = 6591, website = 'https://golf.tooelecity.gov/the_course/index.php', updated_at = CURRENT_TIMESTAMP
WHERE external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db'
   OR (state_code = 'UT' AND LOWER(name) = 'oquirrh hills golf course');

UPDATE golf_course_holes
SET active = 0, updated_at = CURRENT_TIMESTAMP
WHERE course_id IN (
  SELECT id FROM golf_courses
   WHERE external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db'
      OR (state_code = 'UT' AND LOWER(name) = 'oquirrh hills golf course')
);

INSERT INTO golf_course_holes (id, course_id, source, hole_number, tee_name, tee_color, par, yards, stroke_index, active)
SELECT d.id, d.course_id, d.source, d.hole_number, d.tee_name, d.tee_color, d.par, d.yards, d.stroke_index, d.active
FROM (
SELECT 'oquirrh-tooele-default-01' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 1 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 5 AS par, 475 AS yards, 17 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-02' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 2 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 3 AS par, 160 AS yards, 5 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-03' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 3 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 4 AS par, 318 AS yards, 15 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-04' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 4 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 4 AS par, 415 AS yards, 7 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-05' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 5 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 4 AS par, 355 AS yards, 11 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-06' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 6 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 4 AS par, 428 AS yards, 1 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-07' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 7 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 5 AS par, 542 AS yards, 13 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-08' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 8 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 4 AS par, 394 AS yards, 9 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-09' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 9 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 3 AS par, 240 AS yards, 3 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-10' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 10 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 4 AS par, 350 AS yards, 16 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-11' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 11 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 4 AS par, 345 AS yards, 10 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-12' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 12 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 4 AS par, 398 AS yards, 4 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-13' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 13 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 3 AS par, 185 AS yards, 2 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-14' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 14 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 5 AS par, 575 AS yards, 8 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-15' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 15 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 3 AS par, 156 AS yards, 18 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-16' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 16 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 4 AS par, 355 AS yards, 12 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-17' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 17 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 5 AS par, 550 AS yards, 6 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-default-18' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 18 AS hole_number, 'default' AS tee_name, 'default' AS tee_color, 4 AS par, 350 AS yards, 14 AS stroke_index, 1 AS active
) d
ON DUPLICATE KEY UPDATE
  tee_color = VALUES(tee_color), par = VALUES(par), yards = VALUES(yards), stroke_index = VALUES(stroke_index), active = 1, updated_at = CURRENT_TIMESTAMP;

INSERT INTO golf_course_holes (id, course_id, source, hole_number, tee_name, tee_color, par, yards, stroke_index, active)
SELECT d.id, d.course_id, d.source, d.hole_number, d.tee_name, d.tee_color, d.par, d.yards, d.stroke_index, d.active
FROM (
SELECT 'oquirrh-tooele-slag-01' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 1 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 5 AS par, 475 AS yards, 17 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-02' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 2 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 3 AS par, 160 AS yards, 5 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-03' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 3 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 4 AS par, 318 AS yards, 15 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-04' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 4 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 4 AS par, 415 AS yards, 7 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-05' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 5 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 4 AS par, 355 AS yards, 11 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-06' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 6 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 4 AS par, 428 AS yards, 1 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-07' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 7 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 5 AS par, 542 AS yards, 13 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-08' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 8 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 4 AS par, 394 AS yards, 9 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-09' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 9 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 3 AS par, 240 AS yards, 3 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-10' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 10 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 4 AS par, 350 AS yards, 16 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-11' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 11 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 4 AS par, 345 AS yards, 10 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-12' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 12 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 4 AS par, 398 AS yards, 4 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-13' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 13 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 3 AS par, 185 AS yards, 2 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-14' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 14 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 5 AS par, 575 AS yards, 8 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-15' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 15 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 3 AS par, 156 AS yards, 18 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-16' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 16 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 4 AS par, 355 AS yards, 12 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-17' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 17 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 5 AS par, 550 AS yards, 6 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-slag-18' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 18 AS hole_number, 'Slag' AS tee_name, 'slag' AS tee_color, 4 AS par, 350 AS yards, 14 AS stroke_index, 1 AS active
) d
ON DUPLICATE KEY UPDATE
  tee_color = VALUES(tee_color), par = VALUES(par), yards = VALUES(yards), stroke_index = VALUES(stroke_index), active = 1, updated_at = CURRENT_TIMESTAMP;

INSERT INTO golf_course_holes (id, course_id, source, hole_number, tee_name, tee_color, par, yards, stroke_index, active)
SELECT d.id, d.course_id, d.source, d.hole_number, d.tee_name, d.tee_color, d.par, d.yards, d.stroke_index, d.active
FROM (
SELECT 'oquirrh-tooele-copper-01' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 1 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 5 AS par, 465 AS yards, 17 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-02' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 2 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 3 AS par, 145 AS yards, 5 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-03' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 3 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 4 AS par, 312 AS yards, 15 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-04' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 4 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 4 AS par, 408 AS yards, 7 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-05' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 5 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 4 AS par, 333 AS yards, 11 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-06' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 6 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 4 AS par, 387 AS yards, 1 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-07' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 7 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 5 AS par, 505 AS yards, 13 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-08' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 8 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 4 AS par, 364 AS yards, 9 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-09' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 9 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 3 AS par, 175 AS yards, 3 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-10' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 10 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 4 AS par, 334 AS yards, 16 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-11' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 11 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 4 AS par, 327 AS yards, 10 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-12' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 12 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 4 AS par, 365 AS yards, 4 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-13' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 13 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 3 AS par, 154 AS yards, 2 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-14' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 14 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 5 AS par, 469 AS yards, 8 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-15' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 15 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 3 AS par, 140 AS yards, 18 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-16' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 16 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 4 AS par, 318 AS yards, 12 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-17' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 17 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 5 AS par, 518 AS yards, 6 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-copper-18' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 18 AS hole_number, 'Copper' AS tee_name, 'copper' AS tee_color, 4 AS par, 329 AS yards, 14 AS stroke_index, 1 AS active
) d
ON DUPLICATE KEY UPDATE
  tee_color = VALUES(tee_color), par = VALUES(par), yards = VALUES(yards), stroke_index = VALUES(stroke_index), active = 1, updated_at = CURRENT_TIMESTAMP;

INSERT INTO golf_course_holes (id, course_id, source, hole_number, tee_name, tee_color, par, yards, stroke_index, active)
SELECT d.id, d.course_id, d.source, d.hole_number, d.tee_name, d.tee_color, d.par, d.yards, d.stroke_index, d.active
FROM (
SELECT 'oquirrh-tooele-lead-01' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 1 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 5 AS par, 425 AS yards, 17 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-02' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 2 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 3 AS par, 130 AS yards, 5 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-03' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 3 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 4 AS par, 300 AS yards, 15 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-04' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 4 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 4 AS par, 338 AS yards, 7 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-05' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 5 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 4 AS par, 300 AS yards, 11 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-06' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 6 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 4 AS par, 342 AS yards, 1 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-07' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 7 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 5 AS par, 468 AS yards, 13 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-08' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 8 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 4 AS par, 345 AS yards, 9 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-09' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 9 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 3 AS par, 164 AS yards, 3 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-10' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 10 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 4 AS par, 302 AS yards, 16 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-11' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 11 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 4 AS par, 310 AS yards, 10 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-12' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 12 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 4 AS par, 335 AS yards, 4 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-13' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 13 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 3 AS par, 115 AS yards, 2 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-14' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 14 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 5 AS par, 440 AS yards, 8 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-15' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 15 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 3 AS par, 124 AS yards, 18 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-16' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 16 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 4 AS par, 278 AS yards, 12 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-17' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 17 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 5 AS par, 453 AS yards, 6 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-lead-18' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 18 AS hole_number, 'Lead' AS tee_name, 'lead' AS tee_color, 4 AS par, 316 AS yards, 14 AS stroke_index, 1 AS active
) d
ON DUPLICATE KEY UPDATE
  tee_color = VALUES(tee_color), par = VALUES(par), yards = VALUES(yards), stroke_index = VALUES(stroke_index), active = 1, updated_at = CURRENT_TIMESTAMP;

INSERT INTO golf_course_holes (id, course_id, source, hole_number, tee_name, tee_color, par, yards, stroke_index, active)
SELECT d.id, d.course_id, d.source, d.hole_number, d.tee_name, d.tee_color, d.par, d.yards, d.stroke_index, d.active
FROM (
SELECT 'oquirrh-tooele-brick-01' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 1 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 5 AS par, 392 AS yards, 17 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-02' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 2 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 3 AS par, 95 AS yards, 5 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-03' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 3 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 4 AS par, 292 AS yards, 15 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-04' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 4 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 4 AS par, 294 AS yards, 7 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-05' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 5 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 4 AS par, 262 AS yards, 11 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-06' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 6 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 4 AS par, 317 AS yards, 1 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-07' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 7 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 5 AS par, 435 AS yards, 13 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-08' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 8 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 4 AS par, 308 AS yards, 9 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-09' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 9 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 3 AS par, 140 AS yards, 3 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-10' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 10 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 4 AS par, 270 AS yards, 16 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-11' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 11 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 4 AS par, 268 AS yards, 10 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-12' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 12 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 4 AS par, 306 AS yards, 4 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-13' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 13 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 3 AS par, 85 AS yards, 2 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-14' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 14 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 5 AS par, 415 AS yards, 8 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-15' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 15 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 3 AS par, 82 AS yards, 18 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-16' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 16 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 4 AS par, 233 AS yards, 12 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-17' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 17 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 5 AS par, 424 AS yards, 6 AS stroke_index, 1 AS active
UNION ALL
SELECT 'oquirrh-tooele-brick-18' AS id, (SELECT c2.id FROM golf_courses c2 WHERE c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' OR (c2.state_code = 'UT' AND LOWER(c2.name) = 'oquirrh hills golf course') ORDER BY CASE WHEN c2.external_course_id = '9e7dfbad-41a3-43b8-a47b-1740c11cf3db' THEN 0 ELSE 1 END LIMIT 1) AS course_id, 'tooele-city-correction' AS source, 18 AS hole_number, 'Brick' AS tee_name, 'brick' AS tee_color, 4 AS par, 292 AS yards, 14 AS stroke_index, 1 AS active
) d
ON DUPLICATE KEY UPDATE
  tee_color = VALUES(tee_color), par = VALUES(par), yards = VALUES(yards), stroke_index = VALUES(stroke_index), active = 1, updated_at = CURRENT_TIMESTAMP;
