CREATE TABLE IF NOT EXISTS social_platform_connections (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  platform VARCHAR(32) NOT NULL,
  account_id VARCHAR(191) NULL,
  account_name VARCHAR(191) NULL,
  access_token_ciphertext LONGTEXT NULL,
  refresh_token_ciphertext LONGTEXT NULL,
  token_type VARCHAR(32) NULL,
  access_token_expires_at DATETIME NULL,
  refresh_token_expires_at DATETIME NULL,
  scopes_json LONGTEXT NULL,
  metadata_json LONGTEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'connected',
  last_refreshed_at DATETIME NULL,
  last_verified_at DATETIME NULL,
  last_error TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_social_platform_connections_platform (platform),
  INDEX idx_social_platform_connections_status (status),
  INDEX idx_social_platform_connections_access_expiry (access_token_expires_at),
  INDEX idx_social_platform_connections_refresh_expiry (refresh_token_expires_at)
);

CREATE TABLE IF NOT EXISTS social_publications (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  scheduled_job_run_id VARCHAR(64) NOT NULL,
  job_id VARCHAR(80) NOT NULL,
  platform VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  source_file_relative_path VARCHAR(512) NOT NULL,
  title VARCHAR(191) NULL,
  caption TEXT NULL,
  platform_media_id VARCHAR(255) NULL,
  platform_post_id VARCHAR(255) NULL,
  platform_url TEXT NULL,
  error_message TEXT NULL,
  next_attempt_at DATETIME NULL,
  published_at DATETIME NULL,
  correlation_id VARCHAR(128) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_social_publications_run_platform (scheduled_job_run_id, platform),
  INDEX idx_social_publications_job_created (job_id, created_at),
  INDEX idx_social_publications_status_retry (status, next_attempt_at),
  INDEX idx_social_publications_correlation (correlation_id)
);
