CREATE TABLE IF NOT EXISTS scorecard_hole_drafts (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  created_by_user_id VARCHAR(191) NOT NULL,
  created_by_email VARCHAR(191) NOT NULL,
  mode ENUM('team','solo') NOT NULL,
  date DATE NOT NULL,
  state VARCHAR(8) NOT NULL,
  course VARCHAR(191) NOT NULL,
  team VARCHAR(191) NULL,
  opponent_team VARCHAR(191) NULL,
  team_key VARCHAR(191) NOT NULL DEFAULT '',
  opponent_team_key VARCHAR(191) NOT NULL DEFAULT '',
  hole_number TINYINT UNSIGNED NOT NULL,
  par TINYINT UNSIGNED NULL,
  yards SMALLINT UNSIGNED NULL,
  stroke_index TINYINT UNSIGNED NULL,
  score INT NOT NULL,
  score_provided TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_scorecard_hole_drafts_context_lookup (created_by_user_id, mode, date, state, course(160), team_key(160), opponent_team_key(160)),
  INDEX idx_scorecard_hole_drafts_user_date (created_by_user_id, date),
  INDEX idx_scorecard_hole_drafts_course (state, course)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
